version: '3.9'

services:
  php:
    image: symfony/blog
    volumes:
      - ".:/app"
      - "./php.ini:/usr/local/etc/php/php.ini"
    working_dir: /app

  nginx:
    image: nginx:1.17.0
    volumes:
      - ".:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - "php"

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-blog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-blogxx}
      POSTGRES_USER: ${POSTGRES_USER:-blogxx}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_SERVER_NAME: database
      PGADMIN_DEFAULT_EMAIL: admin@blog.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6790:80"
    depends_on:
      - "database"
    volumes:
      - "pgadmin4-data:/var/lib/pgadmin"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
  pgadmin4-data:
